# -*- coding: utf-8 -*-
"""MyApp_Lime.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EegL4LhAMWTFk6pzWGB7Q3X2PLOFX9N
"""

# ==============================================================================
# FINAL APP NOTEBOOK (with LIME)
# ==============================================================================

# PART 1: Install Libraries
!pip install streamlit pyngrok scikit-learn pandas joblib lime -q
print("✅ Step 1/5: All libraries installed.")

# PART 2: Configure Ngrok with your Authtoken
from pyngrok import ngrok
# --- PASTE YOUR NGROK AUTHTOKEN HERE ---
authtoken = "33L2zA1zPtehsWCCq14XL8QW35X_eigQXn3wP8FMTT4QHRYE"
ngrok.set_auth_token(authtoken)
print("✅ Step 2/5: Ngrok token configured.")

# PART 3: Mount Drive and Copy Final Files
from google.colab import drive
import shutil

drive.mount('/content/drive')
try:
    shutil.copyfile('/content/drive/MyDrive/CapstoneProject/mimic_model.joblib', './mimic_model.joblib')
    shutil.copyfile('/content/drive/MyDrive/CapstoneProject/mimic_feature_names.joblib', './mimic_feature_names.joblib')
    print("✅ Step 3/5: Final model and feature names copied successfully.")
except FileNotFoundError as e:
    print(f"❌ Step 3/5: Failed to copy files. Please ensure the 'Training Notebook' ran successfully and created the files. Error: {e}")
    raise

# PART 4: Write the final app.py file
app_code = """
import streamlit as st
import pandas as pd
import joblib
import lime
import lime.lime_tabular
import numpy as np
import streamlit.components.v1 as components

def main():
    try:
        model = joblib.load('mimic_model.joblib')
        feature_names = joblib.load('mimic_feature_names.joblib')
    except Exception as e:
        st.error(f"An error occurred loading the local model files: {e}")
        return

    # Create the LIME explainer inside the app using the loaded feature names
    explainer = lime.lime_tabular.LimeTabularExplainer(
        training_data=np.zeros((1, len(feature_names))), # Dummy data, as LIME just needs an array shape
        feature_names=feature_names,
        class_names=['Survived', 'Expired'],
        mode='classification'
    )

    st.set_page_config(page_title="Mortality Prediction", layout="wide")
    st.title('🩺 AI Clinical Support: Heart Failure Mortality Prediction (MIMIC-III)')
    st.write("Enter patient data in the sidebar to generate a risk score and a LIME explanation.")

    st.sidebar.header('Patient Input Features')

    def user_input_features():
        age = st.sidebar.slider('Age', 20, 100, 65)
        gender = st.sidebar.selectbox('Gender', ('M', 'F'))
        # Lab values
        bicarbonate_avg = st.sidebar.slider('Bicarbonate_avg (mEq/L)', 15.0, 40.0, 25.0, 0.1)
        creatinine_avg = st.sidebar.slider('Creatinine_avg (mg/dL)', 0.4, 10.0, 1.2, 0.1)
        potassium_avg = st.sidebar.slider('Potassium_avg (mEq/L)', 2.5, 7.0, 4.0, 0.1)
        sodium_avg = st.sidebar.slider('Sodium_avg (mEq/L)', 120.0, 155.0, 138.0, 0.1)
        bun_avg = st.sidebar.slider('Urea_Nitrogen_avg (mg/dL)', 5.0, 100.0, 20.0, 0.1)
        # Vitals from chartevents
        systolic_bp = st.sidebar.slider('Systolic_BP (mmHg)', 80.0, 220.0, 120.0, 0.1)
        diastolic_bp = st.sidebar.slider('Diastolic_BP (mmHg)', 40.0, 130.0, 80.0, 0.1)
        bmi = st.sidebar.slider('BMI', 15.0, 50.0, 25.0, 0.1)

        gender_numeric = 0 if gender == 'M' else 1

        data = {
            'age': age,
            'gender': gender_numeric,
            'Bicarbonate_avg': bicarbonate_avg,
            'Creatinine_avg': creatinine_avg,
            'Potassium_avg': potassium_avg,
            'Sodium_avg': sodium_avg,
            'Urea_Nitrogen_avg': bun_avg,
            'Systolic_BP': systolic_bp,
            'Diastolic_BP': diastolic_bp,
            'BMI': bmi
        }
        features = pd.DataFrame(data, index=[0])
        return features[feature_names] # Ensure correct column order

    input_df = user_input_features()
    st.subheader('Patient Input Summary')
    st.write(input_df)

    if st.button('**Predict Patient Risk**'):
        prediction_proba = model.predict_proba(input_df)
        high_risk_probability = prediction_proba[0][1]

        st.subheader('Risk Prediction')
        st.write(f"The model predicts a **{high_risk_probability*100:.1f}%** risk of in-hospital mortality.")

        if high_risk_probability > 0.25:
            st.error('**High Mortality Risk Detected**')
        else:
            st.success('**Low Mortality Risk Detected**')

        st.subheader('LIME Explanation')
        st.write("This shows the features that most contributed to this specific prediction.")

        with st.spinner('Generating explanation...'):
            try:
                # Explain the prediction for the 'Expired' class (class 1)
                explanation = explainer.explain_instance(input_df.iloc[0].values, model.predict_proba, num_features=len(feature_names), labels=(1,))

                # Display the explanation as an HTML component
                components.html(explanation.as_html(), height=400)
            except Exception as e:
                st.error(f"Could not generate the LIME explanation. Error: {e}")

if __name__ == '__main__':
    main()
"""
with open('app.py', 'w') as f:
    f.write(app_code)

print("✅ Step 4/5: Streamlit app file (app.py) created successfully.")

# PART 5: Launch the App
ngrok.kill()
public_url = ngrok.connect(8501)
print(f"✅ Step 5/5: Your app is live! Click this link to open it: {public_url}")
!streamlit run app.py --server.runOnSave true